# Generated by Django 2.0.3 on 2018-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_week', models.CharField(max_length=50)),
                ('last_week', models.TextField()),
                ('next_week', models.TextField()),
                ('created_user', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
